### ISSUE TITLE
Bug in cca_by_svd computation

### ISSUE THREAD

**Issue by brando90** [moskomule/anatome#27]
I am computing two random matrices that are different and totally random. Their CCA shouldn't be high since they are different and random. Google's svcca library gives me much lower CCA values but anatome's gives me CCA values that are 1.0...which obviously are wrong. Any idea where the bug might be? Been looking for it for a while:

Code:
```
#%%
import torch
from matplotlib import pyplot as plt

from uutils.torch_uu.metrics.cca import cca_core

from torch import Tensor
from anatome.similarity import svcca_distance, cca_by_svd, cca_by_qr, _compute_cca_traditional_equation
import numpy as np
import random
np.random.seed(0)
torch.manual_seed(0)
random.seed(0)


# tutorial shapes (500, 10000) (500, 10000) based on MNIST with 500 neurons from a FCNN
D, N = 500, 10_000

# - creating a random baseline
# b1 = np.random.randn(*acts1.shape)
# b2 = np.random.randn(*acts2.shape)
b1 = np.random.randn(D, N)
b2 = np.random.randn(D, N)
print('-- reproducibity finger print')
print(f'{b1.sum()=}')
print(f'{b2.sum()=}')
print(f'{b1.shape=}')

# - get cca values for baseline
print("\n-- Google's SVCCA -- ")
baseline = cca_core.get_cca_similarity(b1, b2, epsilon=1e-10, verbose=False)
# _plot_helper(baseline["cca_coef1"], "CCA coef idx", "CCA coef value")
# print("Baseline Mean CCA similarity", np.mean(baseline["cca_coef1"]))
# print("Baseline CCA similarity", baseline["cca_coef1"])
print(f'{len(baseline["cca_coef1"])=}')
print("Baseline CCA similarity", baseline["cca_coef1"][:6])
print(f"{np.mean(baseline['cca_coef1'])=}")

# - get sklern's cca's https://scikit-learn.org/stable/modules/generated/sklearn.cross_decomposition.CCA.html
# from sklearn.cross_decomposition import CCA
# # cca = CCA(n_components=D)
# cca = CCA(n_components=6)
# cca.fit(b1, b2)

# -
print("\n-- Ultimate Anatome's SVCCA --")
# 'svcca': partial(svcca_distance, accept_rate=0.99, backend='svd')
# svcca_dist: Tensor = svcca_distance(x, y, accept_rate=0.99, backend='svd')
b1_t, b2_t = torch.from_numpy(b1), torch.from_numpy(b2)
# svcca: Tensor = 1.0 - svcca_distance(x=b1_t, y=b2_t, accept_rate=1.0, backend='svd')
# diag: Tensor = svcca_distance(x=b1_t, y=b2_t, accept_rate=0.99, backend='svd')
# a, b, diag = cca(x, y, backend='svd')
a, b, diag = cca_by_svd(b1_t, b2_t)
# a, b, diag = cca_by_qr(b1_t, b2_t)
# diag = _compute_cca_traditional_equation(b1_t, b2_t)
print(f'{diag.size()=}')
print(f'{diag[:6]=}')
print(f'{diag.mean()}')
# print(f'{svcca=}')

print()
```
output
```
-- reproducibity finger print
b1.sum()=686.0427476883059
b2.sum()=2341.981561471438
b1.shape=(500, 10000)
-- Google's SVCCA -- 
len(baseline["cca_coef1"])=500
Baseline CCA similarity [0.43056735 0.42918498 0.42502398 0.42290128 0.42208184 0.41986944]
np.mean(baseline['cca_coef1'])=0.19071397156414877
-- Ultimate Anatome's SVCCA --
diag.size()=torch.Size([500])
diag[:6]=tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000], dtype=torch.float64)
1.0
```

**Comment by moskomule** [comment]
Can you check the dev branch? I fixed a bug.

**Comment by brando90** [comment]
> Can you check the dev branch? I fixed a bug.

ok will do it now.

Note for myself, installing dev branch do ` pip install -U git+https://github.com/moskomule/anatome.git@dev ` https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch

**Comment by brando90** [comment]
@moskomule bug is still present. See output (I also make sure I am using your anatome by printing the version from within python):
```
(original_anatome_env) brando~/ultimate-utils/ultimate-utils-proj-src ❯ python /Users/brando/ultimate-anatome/sanity_checks/sanity_cca_ulitmate_anatome_vs_maithra_vs_scipy.py
-- anatome being used --
anatome                 0.0.6
anatome=<module 'anatome' from '/Users/brando/anaconda3/envs/metalearning/envs/original_anatome_env/lib/python3.9/site-packages/anatome/__init__.py'>
("sys.path=['/Users/brando/ultimate-anatome/sanity_checks', "
 "'/Users/brando/anaconda3/envs/metalearning/envs/original_anatome_env/lib/python39.zip', "
 "'/Users/brando/anaconda3/envs/metalearning/envs/original_anatome_env/lib/python3.9', "
 "'/Users/brando/anaconda3/envs/metalearning/envs/original_anatome_env/lib/python3.9/lib-dynload', "
 "'/Users/brando/anaconda3/envs/metalearning/envs/original_anatome_env/lib/python3.9/site-packages', "
 "'/Users/brando/ultimate-utils/ultimate-utils-proj-src']")

-- start cca test --
-- reproducibity finger print
b1.sum()=686.0427476883059
b2.sum()=2341.981561471438
b1.shape=(500, 10000)

-- Google's SVCCA -- 
len(baseline["cca_coef1"])=500
Baseline CCA similarity [0.43056735 0.42918498 0.42502398 0.42290128 0.42208184 0.41986944]
np.mean(baseline['cca_coef1'])=0.19071397156414885

-- Ultimate Anatome's SVCCA --
diag.size()=torch.Size([500])
diag[:6]=tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000], dtype=torch.float64)
diag.mean()=tensor(1., dtype=torch.float64)
```

updated code to run that:
```
"""
Some experiment results seem funny with PWCCA so let's make sure the CCA values for of ultimate anatome matches or is
close to values of other code.

conda install pytorch torchvision torchaudio -c pytorch

conda install pytorch torchvision torchaudio -c pytorch==1.10
"""
#%%
import sys
from pprint import pprint

import torch
from matplotlib import pyplot as plt

from uutils.torch_uu.metrics.cca import cca_core

from torch import Tensor
# from anatome.similarity import svcca_distance, cca_by_svd, cca_by_qr, _compute_cca_traditional_equation
from anatome.distance import svcca_distance, cca_by_svd, cca_by_qr
import numpy as np
import random
np.random.seed(0)
torch.manual_seed(0)
random.seed(0)

# - checking anatome being uses
print('-- anatome being used --')
import os
os.system('pip list | grep anatome')
import anatome
print(f'{anatome=}')
pprint(f'{sys.path=}')
# print(f'{anatome.__version__=}')
# import subprocess
# print(subprocess.check_output(['ls', '-l']))

print('\n-- start cca test --')


# tutorial shapes (500, 10000) (500, 10000) based on MNIST with 500 neurons from a FCNN
D, N = 500, 10_000

# - creating a random baseline
# b1 = np.random.randn(*acts1.shape)
# b2 = np.random.randn(*acts2.shape)
b1 = np.random.randn(D, N)
b2 = np.random.randn(D, N)
print('-- reproducibity finger print')
print(f'{b1.sum()=}')
print(f'{b2.sum()=}')
print(f'{b1.shape=}')

# - get cca values for baseline
print("\n-- Google's SVCCA -- ")
baseline = cca_core.get_cca_similarity(b1, b2, epsilon=1e-10, verbose=False)
# _plot_helper(baseline["cca_coef1"], "CCA coef idx", "CCA coef value")
# print("Baseline Mean CCA similarity", np.mean(baseline["cca_coef1"]))
# print("Baseline CCA similarity", baseline["cca_coef1"])
print(f'{len(baseline["cca_coef1"])=}')
print("Baseline CCA similarity", baseline["cca_coef1"][:6])
print(f"{np.mean(baseline['cca_coef1'])=}")

# - get sklern's cca's https://scikit-learn.org/stable/modules/generated/sklearn.cross_decomposition.CCA.html
# from sklearn.cross_decomposition import CCA
# # cca = CCA(n_components=D)
# cca = CCA(n_components=6)
# cca.fit(b1, b2)

# -
print("\n-- Ultimate Anatome's SVCCA --")
# 'svcca': partial(svcca_distance, accept_rate=0.99, backend='svd')
# svcca_dist: Tensor = svcca_distance(x, y, accept_rate=0.99, backend='svd')
b1_t, b2_t = torch.from_numpy(b1), torch.from_numpy(b2)
# svcca: Tensor = 1.0 - svcca_distance(x=b1_t, y=b2_t, accept_rate=1.0, backend='svd')
# diag: Tensor = svcca_distance(x=b1_t, y=b2_t, accept_rate=0.99, backend='svd')
# a, b, diag = cca(x, y, backend='svd')
a, b, diag = cca_by_svd(b1_t, b2_t)
# a, b, diag = cca_by_qr(b1_t, b2_t)
# diag = _compute_cca_traditional_equation(b1_t, b2_t)
print(f'{diag.size()=}')
print(f'{diag[:6]=}')
print(f'{diag.mean()=}')
# print(f'{svcca=}')

print()
```

**Comment by brando90** [comment]
the env to reproduce this:
```
pip install ultimate-utils
conda install pytorch torchvision torchaudio -c pytorch
pip install -U git+https://github.com/moskomule/anatome.git@dev
```

**Comment by brando90** [comment]
I think your implementation (assuming the paper you cite http://numerical.recipes/whp/notes/CanonCorrBySVD.pdf is correct) is correct @moskomule but there is some preprocessing that Maithra's SVCCA is doing. Did you check if that makes the difference?

**Comment by brando90** [comment]
btw, this might be of interest to you: https://stackoverflow.com/questions/69800500/how-to-calculate-correlation-coefficients-using-sklearn-cca-module for additional sanity checks.

**Comment by brando90** [comment]
I can confirm the cca part of the code is working:
```
-- start cca test --
-- reproducibity finger print
b1.sum()=7.027963615654894
b2.sum()=-1.047162062206396
b1.shape=(5, 10)
-- Google's CCA -- 
len(baseline["cca_coef1"])=5
Baseline CCA similarity [1.         0.99170084 0.87896549 0.44275458 0.00618966]
np.mean(baseline['cca_coef1'])=0.6639221147284049
-- Ultimate Anatome's CCA --
diag.size()=torch.Size([5])
diag[:5]=tensor([1.0000, 0.9917, 0.8790, 0.4428, 0.0062], dtype=torch.float64)
diag.mean()=tensor(0.6639, dtype=torch.float64)
```
code:
```
"""
Some experiment results seem funny with PWCCA so let's make sure the CCA values for of ultimate anatome matches or is
close to values of other code.

conda install pytorch torchvision torchaudio -c pytorch

conda install pytorch torchvision torchaudio -c pytorch==1.10
"""
#%%
import sys
from pprint import pprint

import torch
from matplotlib import pyplot as plt

from uutils.torch_uu import approx_equal
from uutils.torch_uu.metrics.cca import cca_core

from torch import Tensor
from anatome.similarity import svcca_distance, cca_by_svd, cca_by_qr, _compute_cca_traditional_equation, cca
# from anatome.distance import svcca_distance, cca_by_svd, cca_by_qr
import numpy as np
import random
np.random.seed(0)
torch.manual_seed(0)
random.seed(0)

# - checking anatome being uses
print('-- anatome being used --')
import os
os.system('pip list | grep anatome')
import anatome
print(f'{anatome=}')
pprint(f'{sys.path=}')
# print(f'{anatome.__version__=}')
# import subprocess
# print(subprocess.check_output(['ls', '-l']))

print('\n-- start cca test --')


# tutorial shapes (500, 10000) (500, 10000) based on MNIST with 500 neurons from a FCNN
# D, N = 500, 10_000
D, N = 5, 10

# - creating a random baseline
# b1 = np.random.randn(*acts1.shape)
# b2 = np.random.randn(*acts2.shape)
b1 = np.random.randn(D, N)
b2 = np.random.randn(D, N)
print('-- reproducibity finger print')
print(f'{b1.sum()=}')
print(f'{b2.sum()=}')
print(f'{b1.shape=}')

# - get cca values for baseline
print("\n-- Google's CCA -- ")
baseline = cca_core.get_cca_similarity(b1, b2, epsilon=1e-10, verbose=False)
# _plot_helper(baseline["cca_coef1"], "CCA coef idx", "CCA coef value")
# print("Baseline Mean CCA similarity", np.mean(baseline["cca_coef1"]))
# print("Baseline CCA similarity", baseline["cca_coef1"])
print(f'{len(baseline["cca_coef1"])=}')
print("Baseline CCA similarity", baseline["cca_coef1"][:5])
print(f"{np.mean(baseline['cca_coef1'])=}")

# - get sklern's cca's https://scikit-learn.org/stable/modules/generated/sklearn.cross_decomposition.CCA.html, https://stackoverflow.com/questions/69800500/how-to-calculate-correlation-coefficients-using-sklearn-cca-module
# from sklearn.cross_decomposition import CCA
# # cca = CCA(n_components=D)
# cca = CCA(n_components=6)
# cca.fit(b1, b2)

# -
print("\n-- Ultimate Anatome's CCA --")
b1_t, b2_t = torch.from_numpy(b1).T, torch.from_numpy(b2).T
assert(b1_t.size() == torch.Size([N, D]))
# svcca_dist: Tensor = svcca_distance(x, y, accept_rate=0.99, backend='svd')
# svcca: Tensor = 1.0 - svcca_distance(x=b1_t, y=b2_t, accept_rate=1.0, backend='svd')
# diag: Tensor = svcca_distance(x=b1_t, y=b2_t, accept_rate=0.99, backend='svd')
a, b, diag = cca(x=b1_t, y=b2_t, backend='svd')
# a, b, diag = cca_by_svd(b1_t, b2_t)
# a, b, diag = cca_by_qr(b1_t, b2_t)
print(f'{diag.size()=}')
print(f'{diag[:5]=}')
print(f'{diag.mean()=}')
assert (approx_equal(diag.mean(), np.mean(baseline['cca_coef1'])))

# -
# print("\n-- Tranditional CCA eqs in PyTorch --")
# diag = _compute_cca_traditional_equation(b1_t, b2_t)
# print(f'{diag.size()=}')
# print(f'{diag[:5]=}')
# print(f'{diag.mean()=}')

print()
```

note I didn't change anything...so it's puzzling what was wrong, perhaps using anatome's interface incorrectly...but I left the division by max because it seems benign and it doesn't affect results.

**Comment by moskomule** [comment]
Yes, my implementation is based on that paper. I think as you guess the additional preprocessing makes the change. For example, the current implementation accepts the following test:

```python
a = torch.randn(100, 50)
b = a.roll(1, 1)
distance.svcca_distance(a, b, 0.99, "svd")
# tensor(0.)

b = torch.randn_like(a)
distance.svcca_distance(a, b, 0.99, "svd")
# tensor(0.1726)
```

**Comment by brando90** [comment]
@moskomule 

more good news, your code seems to match again with svcca of google:
```
-- start cca test --
NOTE: original tutorial does NOT center random baseline for these experiments, probably a combination ofcarelessness/bug or that it doesnt matter for these since b1, b2 are already centered. Tough the also forgot to center the MNIST activations, but due to BN I suspect it doesnt make a big difference.
-- reproducibity finger print
b1.sum()=8.881784197001252e-16
b2.sum()=1.5543122344752192e-15
b1.shape=(7, 12)
-- Google's CCA -- 
len(baseline["cca_coef1"])=7
Baseline CCA similarity [1.         1.         1.         0.88916509 0.68977494]
np.mean(baseline['cca_coef1'])=0.679365212036018
-- Ultimate Anatome's CCA --
diag.size()=torch.Size([7])
diag[:dims_to_keep]=tensor([1.0000, 1.0000, 1.0000, 0.8892, 0.6898], dtype=torch.float64)
diag.mean()=tensor(0.6794, dtype=torch.float64)
extra test with acceptance_rate=1.0: svcca_uanatome=tensor(0.7374, dtype=torch.float64) should be close to 0.679365212036018
---- Google's SVCCA test1 (# of num_dims to keep hardcoded instead of via variance to keep) ---- 
svcca_keeping_fixed_dims=0.6434242311722723
---- Ultimate Anatome's SVCCA test1 (# of num_dims to keep hardcoded instead of via variance to keep) ----
svcca_uanatome_keeping_fixed_dims_original_anatome=tensor(0.6434, dtype=torch.float64)
svcca_uanatome_keeping_fixed_dims_original_svcca=tensor(0.6434, dtype=torch.float64)
```

I did thorough experiments changing many of the details and all changes didn't affect it. So svcca code is good.

There seems to be a mistmatch with pwcca which will be resolved in a few hours. :)

**Comment by brando90** [comment]
> Yes, my implementation is based on that paper. I think as you guess the additional preprocessing makes the change. For example, the current implementation passes the following test:
> 
> ```python
> a = torch.randn(100, 50)
> b = a.roll(1, 1)
> distance.svcca_distance(a, b, 0.99, "svd")
> # tensor(0.)
> 
> b = torch.randn_like(a)
> distance.svcca_distance(a, b, 0.99, "svd")
> # tensor(0.1726)
> ```

I don't think dividing by max makes a difference. I've made lots of changes and everything seems fine. No need to worry but dividing by max does not hurt for sure and that is what I do do in my final code because why not more numerical stability?

**Comment by brando90** [comment]
will need to debug pwcca until monday....thats the one giving me issues in my real research though...

**Comment by brando90** [comment]
The difference is here:
```
def compute_pwcca(acts1, acts2, epsilon=0.):
    """ Computes projection weighting for weighting CCA coefficients 
    
    Args:
         acts1: 2d numpy array, shaped (neurons, num_datapoints)
	 acts2: 2d numpy array, shaped (neurons, num_datapoints)

    Returns:
	 Original cca coefficient mean and weighted mean

    """
    sresults = cca_core.get_cca_similarity(acts1, acts2, epsilon=epsilon, 
					   compute_dirns=False, compute_coefs=True, verbose=False)
    if np.sum(sresults["x_idxs"]) <= np.sum(sresults["y_idxs"]):
        dirns = np.dot(sresults["coef_x"], 
                    (acts1[sresults["x_idxs"]] - \
                     sresults["neuron_means1"][sresults["x_idxs"]])) + sresults["neuron_means1"][sresults["x_idxs"]]
        coefs = sresults["cca_coef1"]
        acts = acts1
        idxs = sresults["x_idxs"]
    else:
        dirns = np.dot(sresults["coef_y"], 
                    (acts1[sresults["y_idxs"]] - \
                     sresults["neuron_means2"][sresults["y_idxs"]])) + sresults["neuron_means2"][sresults["y_idxs"]]
        coefs = sresults["cca_coef2"]
        acts = acts2
        idxs = sresults["y_idxs"]
    P, _ = np.linalg.qr(dirns.T)
    weights = np.sum(np.abs(np.dot(P.T, acts[idxs].T)), axis=1)
    weights = weights/np.sum(weights)
    
    return np.sum(weights*coefs), weights, coefs
```

can't make them match yet:
```
------ Google's PWCCA test  ------ 
pwcca_mean=0.7660273914027722
------ Ultimate Anatome's PWCCA test ------
pwcca_ultimateanatome=tensor(0.6636, dtype=torch.float64)
pwcca_ultimateanatome=tensor(0.6790, dtype=torch.float64)
```

**Comment by brando90** [comment]
yours had a small bug but it wasn't fixed by what I did anyway...
```
def pwcca_distance2(L1: Tensor,
                   L2: Tensor,
                   backend: str
                   ) -> Tensor:
    """ Projection Weighted CCA proposed in Marcos et al. 2018.

    Args:
        x: input tensor of Shape NxD1, where it's recommended that N>Di
        y: input tensor of Shape NxD2, where it's recommended that N>Di
        backend: svd or qr

    Returns:

    """

    a, b, diag = cca(L1, L2, backend)
    # alpha = (x @ a).abs_().sum(dim=0)
    x = L1 @ a
    # x = L2 @ b
    x, _ = torch.linalg.qr(input=x)
    alpha = (x.T @ L1).abs_().sum(dim=1)
    alpha /= alpha.sum()
    return 1 - alpha @ diag
```

**Comment by moskomule** [comment]
OK, they use reorthogonalization.

**Comment by brando90** [comment]
> OK, they orthonormalize.

no:
```
x = L1 @ a
```
they use the CCA vectors not the weights a,b from CCA, then orthonormalize.

Though, I don't think it made a difference when I ran it.

They also choose L1 vs L2 due to some condition:
```
if np.sum(sresults["x_idxs"]) <= np.sum(sresults["y_idxs"]):
```

**Comment by moskomule** [comment]
Summarizing the original paper,

* get L_1=[z_1, ..., z_a]
* compute CCA vectors [h_1, ..., h_c] corresponding to L_1
* reorthonormalize [h_1, ..., h_c]
* compute \alpha_i=\sum_j |<h_i, z_j>|
* d(L_1, L_2) = 1 - \sum_i \alpha_i\rho^{(i)}

Their code means `alpha=(a.T @ L1.T @ L1).abs().sum(dim=1)`, which I think is different from this.

What does `sresults["x_idxs"]` mean?

**Comment by brando90** [comment]
> Summarizing the original paper,
> 
> * get L_1=[z_1, ..., z_a]
> * compute CCA vectors [h_1, ..., h_c] corresponding to L_1
> * reorthonormalize [h_1, ..., h_c]
> * compute \alpha_i=\sum_j |<h_i, z_j>|
> * d(L_1, L_2) = 1 - \sum_i \alpha_i\rho^{(i)}

yes according to the paper I think that is correct (and what I implemented - and you did too basically, the steps you skipped didn't make a big difference as I showed in my program output). BUT, both our approaches make a difference with the original pwcca code and I am seeing some "real experiments" behave weirdly - why I am trying to see if matching their code "fixed it".

**Comment by brando90** [comment]
> What does `sresults["x_idxs"]` mean?

This is what I am trying to figure out but according to their docs:

```
            x_idxs:       The indexes of the input sigma_xx that were pruned
                          by remove_small
            y_idxs:       Same as above but for sigma_yy
```

for completeness the rest of the doc:
```
def compute_ccas(sigma_xx, sigma_xy, sigma_yx, sigma_yy, epsilon,
                 verbose=True):
  """Main cca computation function, takes in variances and crossvariances.

  This function takes in the covariances and cross covariances of X, Y,
  preprocesses them (removing small magnitudes) and outputs the raw results of
  the cca computation, including cca directions in a rotated space, and the
  cca correlation coefficient values.

  Args:
            sigma_xx: 2d numpy array, (num_neurons_x, num_neurons_x)
                      variance matrix for x
            sigma_xy: 2d numpy array, (num_neurons_x, num_neurons_y)
                      crossvariance matrix for x,y
            sigma_yx: 2d numpy array, (num_neurons_y, num_neurons_x)
                      crossvariance matrix for x,y (conj) transpose of sigma_xy
            sigma_yy: 2d numpy array, (num_neurons_y, num_neurons_y)
                      variance matrix for y
            epsilon:  small float to help with stabilizing computations
            verbose:  boolean on whether to print intermediate outputs

  Returns:
            [ux, sx, vx]: [numpy 2d array, numpy 1d array, numpy 2d array]
                          ux and vx are (conj) transposes of each other, being
                          the canonical directions in the X subspace.
                          sx is the set of canonical correlation coefficients-
                          how well corresponding directions in vx, Vy correlate
                          with each other.
            [uy, sy, vy]: Same as above, but for Y space
            invsqrt_xx:   Inverse square root of sigma_xx to transform canonical
                          directions back to original space
            invsqrt_yy:   Same as above but for sigma_yy
            x_idxs:       The indexes of the input sigma_xx that were pruned
                          by remove_small
            y_idxs:       Same as above but for sigma_yy
  """
```

**Comment by brando90** [comment]
Seems what they do is 

> Takes covariance between X, Y, and removes values of small magnitude.

idk why they do that but here it is:

```
def remove_small(sigma_xx, sigma_xy, sigma_yx, sigma_yy, epsilon):
  """Takes covariance between X, Y, and removes values of small magnitude.

  Args:
            sigma_xx: 2d numpy array, variance matrix for x
            sigma_xy: 2d numpy array, crossvariance matrix for x,y
            sigma_yx: 2d numpy array, crossvariance matrixy for x,y,
                      (conjugate) transpose of sigma_xy
            sigma_yy: 2d numpy array, variance matrix for y
            epsilon : cutoff value for norm below which directions are thrown
                       away

  Returns:
            sigma_xx_crop: 2d array with low x norm directions removed
            sigma_xy_crop: 2d array with low x and y norm directions removed
            sigma_yx_crop: 2d array with low x and y norm directiosn removed
            sigma_yy_crop: 2d array with low y norm directions removed
            x_idxs: indexes of sigma_xx that were removed
            y_idxs: indexes of sigma_yy that were removed
  """
```

I might just plug in their code and convert my torch to numpy things to see if that still gives weird results to me. If it does then I think perhaps changing to theirs might not be necessary...

**Comment by brando90** [comment]
they basically choose `L1` or `L2` depending on which one they removed the least small vales from their covariance matrices `sigma_xx` or `sigma_yy.`...not sure why they did that or why it wasn't measured in the paper.

**Comment by moskomule** [comment]
Is this approach (computing covariance of two inputs) scalable?

**Comment by brando90** [comment]
> Is this approach (computing covariance of two inputs) scalable?

no I don't think it is. I've tried something similar and it's really slow...will update in a few minutes I hope.

**Comment by moskomule** [comment]
Yes, I first implemented `cca.pytorch`, the scalability was the problem for a researcher without rich resources.

**Comment by brando90** [comment]
unfortunately couldn't just replace the anatome pwcca with google's, I get errors:
```
/home/miranda9/ultimate-utils/ultimate-utils-proj-src/uutils/torch_uu/metrics/cca/cca_core.py:55: RuntimeWarning: invalid value encountered in sqrt
  wsqrt = np.sqrt(w)
Traceback (most recent call last):
  File "/home/miranda9/automl-meta-learning/results_plots_sl_vs_ml/fall2021/main_dist_sl_vs_maml.py", line 676, in <module>
    main_run_expt()
  File "/home/miranda9/automl-meta-learning/results_plots_sl_vs_ml/fall2021/main_dist_sl_vs_maml.py", line 394, in main_run_expt
    dist_batch_tasks_for_all_layer_mdl_vs_adapted_mdl(
  File "/home/miranda9/ultimate-utils/ultimate-utils-proj-src/uutils/torch_uu/meta_learners/maml_differentiable_optimizer.py", line 298, in dist_batch_tasks_for_all_layer_mdl_vs_adapted_mdl
    dists_per_layer: OrderedDict[LayerIdentifier, float] = dist_data_set_per_layer(mdl1=mdl,
  File "/home/miranda9/ultimate-anatome/anatome/helper.py", line 179, in dist_data_set_per_layer
    dist: float = hook1.distance(hook2,
  File "/home/miranda9/ultimate-anatome/anatome/similarity.py", line 672, in distance
    dist: float = self.cca_function(self_tensor, other_tensor).item()
  File "/home/miranda9/ultimate-anatome/anatome/similarity.py", line 345, in pwcca_distance3
    pwcca, _, _ = compute_pwcca(acts1=acts1, acts2=acts2)
  File "/home/miranda9/ultimate-utils/ultimate-utils-proj-src/uutils/torch_uu/metrics/cca/pwcca.py", line 40, in compute_pwcca
    sresults = cca_core.get_cca_similarity(acts1, acts2, epsilon=epsilon,
  File "/home/miranda9/ultimate-utils/ultimate-utils-proj-src/uutils/torch_uu/metrics/cca/cca_core.py", line 291, in get_cca_similarity
    x_idxs, y_idxs) = compute_ccas(sigmaxx, sigmaxy, sigmayx, sigmayy,
  File "/home/miranda9/ultimate-utils/ultimate-utils-proj-src/uutils/torch_uu/metrics/cca/cca_core.py", line 160, in compute_ccas
    u, s, v = np.linalg.svd(arr)
  File "<__array_function__ internals>", line 5, in svd
  File "/home/miranda9/miniconda3/envs/metalearning_gpu/lib/python3.9/site-packages/numpy/linalg/linalg.py", line 1660, in svd
    u, s, vh = gufunc(a, signature=signature, extobj=extobj)
  File "/home/miranda9/miniconda3/envs/metalearning_gpu/lib/python3.9/site-packages/numpy/linalg/linalg.py", line 97, in _raise_linalgerror_svd_nonconvergence
    raise LinAlgError("SVD did not converge")
numpy.linalg.LinAlgError: SVD did not converge
```
need to think what to do...

**Comment by brando90** [comment]
ok fixed their code by taking square root of matrices with numpy instead of their code https://github.com/google/svcca/pull/10.

**Comment by brando90** [comment]
I can confirm that using their code removes the weird issues I was seeing in my experiments. I think I will be using their pwcca until I get time to fix ours...alas.

**Comment by brando90** [comment]
Ok I think I know how to (nearly!) fix anatome (to match google's code).

This works:
```
def pwcca_distance2(L1: Tensor,
                    L2: Tensor,
                    backend: str,
                    use_layer_matrix: str = 'L1'
                    ) -> Tensor:
    """ Projection Weighted CCA proposed in Marcos et al. 2018.

    Args:
        x: input tensor of Shape NxD1, where it's recommended that N>Di
        y: input tensor of Shape NxD2, where it's recommended that N>Di
        backend: svd or qr

    Returns:

    """

    a, b, diag = cca(L1, L2, backend)
    if use_layer_matrix == 'L1':
        x = L1 @ a
        x, _ = torch.linalg.qr(input=x)
        alpha = (x.T @ L1).abs_().sum(dim=1)
    elif use_layer_matrix == 'L2':
        x = L2 @ b
        x, _ = torch.linalg.qr(input=x)
        alpha = (x.T @ L2).abs_().sum(dim=1)
    else:
        assert ValueError(f'Value {use_layer_matrix=} not valid.')
    alpha /= alpha.sum()
    return 1 - alpha @ diag
```
gives:

```
------ Google's PWCCA test  ------ 
pwcca_mean=0.7660273858851013
------ Ultimate Anatome's PWCCA test ------
pwcca_ultimateanatome=tensor(0.6636, dtype=torch.float64)
pwcca_ultimateanatome=tensor(0.6790, dtype=torch.float64)
pwcca_ultimateanatome=tensor(0.7565, dtype=torch.float64)
pwcca_ultimateanatome=tensor(0.7669, dtype=torch.float64)
```

from
```
print("\n\n------ Google's PWCCA test  ------ ")
pwcca_mean, w, _ = pwcca.compute_pwcca(b1, b2, epsilon=1e-10)
print(f'{pwcca_mean=}')

# ---- PWCCA test3
# -
print("\n------ Ultimate Anatome's PWCCA test ------")
pwcca_ultimateanatome: Tensor = 1.0 - pwcca_distance(x=b1_t, y=b2_t, backend='svd')
print(f'{pwcca_ultimateanatome=}')
pwcca_ultimateanatome: Tensor = 1.0 - pwcca_distance2(b1_t, b2_t, backend='svd', use_layer_matrix='L1')
print(f'{pwcca_ultimateanatome=}')
pwcca_ultimateanatome: Tensor = 1.0 - pwcca_distance2(b1_t, b2_t, backend='svd', use_layer_matrix='L2')
print(f'{pwcca_ultimateanatome=}')
pwcca_ultimateanatome: Tensor = 1.0 - pwcca_distance3(b1_t, b2_t)
print(f'{pwcca_ultimateanatome=}')
```

meaning we just need to approximately figure out which of the two layer matrices L1 or L2 would result in:
```
if np.sum(sresults["x_idxs"]) <= np.sum(sresults["y_idxs"]):
```

something like figuring out which of the two L1 and L2 (covariances) has a diagonal greater than epsilon.

**Comment by brando90** [comment]
it seems that it's very hard to have them match exactly for PWCCA for some reason.

I think it's a numerical issue when things are VERY close to zero e.g. `e-12`. I have confirmed both are using the same layer matrix L1 and they still don't match (in fact the L1 in numpy doesn't seem to be exactly the same as the L1 in torch).

I don't know how to fix it further but here are some results:
```
-------- do they match? --------
b1.sum()=1.2221335055073723e-12
b2.sum()=1.6271428648906294e-12
b1_t.sum()=tensor(1.1937e-12, dtype=torch.float64)
b2_t.sum()=tensor(1.1369e-12, dtype=torch.float64)
--> acts1.sum() = 1.2221335055073723e-12
--> acts2.sum() = 1.6271428648906294e-12
--> acts1.sum() = 1.2221335055073723e-12
--> acts2.sum() = 1.6271428648906294e-12
--> np.sum(sresults["x_idxs"]) <= np.sum(sresults["y_idxs"])=True
--> Using xs
--> acts.sum() = 1.2221335055073723e-12
use_layer_matrix='L1'
==>x_idxs.sum() <= y_idxs.sum()=tensor(True)
==> L1.sum() = tensor(1.1937e-12, dtype=torch.float64)
==> L2.sum() = tensor(1.1369e-12, dtype=torch.float64)
====> L1.sum() = tensor(1.1937e-12, dtype=torch.float64)
Google's (fixed): pwcca_mean2=0.1925180440414785
Our code: pwcca_ultimateanatome=tensor(0.1908, dtype=torch.float64)
```

The pwcca code that matches google approximately by choosing the L1 or L2 with the fewest values removed is:
```
def pwcca_distance2(L1: Tensor,
                    L2: Tensor,
                    backend: str,
                    use_layer_matrix: Optional[str] = None,
                    epsilon: float = 0.0
                    ) -> Tensor:
    """ Projection Weighted CCA proposed in Marcos et al. 2018.

    Args:
        x: input tensor of Shape NxD1, where it's recommended that N>Di
        y: input tensor of Shape NxD2, where it's recommended that N>Di
        backend: svd or qr

    Returns:
    :param use_layer_matrix: L1 for forcing the code to use L1 and L2 for forcing the code to use L2.
    """
    a, b, diag = cca(L1, L2, backend)
    if use_layer_matrix is None:
        # sigma_xx_approx = L1
        # sigma_yy_approx = L2
        sigma_xx_approx = L1.T @ L1
        sigma_yy_approx = L2.T @ L2
        # L1_diag = torch.diag(sigma_xx_approx.abs())
        # L2_diag = torch.diag(sigma_yy_approx.abs())
        L1_diag = torch.diag(sigma_xx_approx.abs())
        L2_diag = torch.diag(sigma_yy_approx.abs())
        x_idxs = (L1_diag >= epsilon)
        y_idxs = (L2_diag >= epsilon)
        # mimicing if np.sum(sresults["x_idxs"]) <= np.sum(sresults["y_idxs"]): i.e.
        # choose layer that had less small values removed, since that affects which layer matrix we use
        # note: we don't remove the small values compared to original svcca which does remove them from sigma_xx, etc.
        use_layer_matrix: str = 'L1' if x_idxs.sum() <= y_idxs.sum() else 'L2'
        print(f'{use_layer_matrix=}')
        print(f'==>{x_idxs.sum() <= y_idxs.sum()=}')
    print(f'==> {L1.sum() = }')
    print(f'==> {L2.sum() = }')
    if use_layer_matrix == 'L1':
        print(f'====> {L1.sum() = }')
        x = L1 @ a
        x, _ = torch.linalg.qr(input=x)
        alpha = (x.T @ L1).abs_().sum(dim=1)
    elif use_layer_matrix == 'L2':
        print(f'====> {L2.sum() = }')
        x = L2 @ b
        x, _ = torch.linalg.qr(input=x)
        alpha = (x.T @ L2).abs_().sum(dim=1)
    else:
        assert ValueError(f'Value {use_layer_matrix=} not valid.')
    alpha /= alpha.sum()
    return 1 - alpha @ diag
```

**Comment by brando90** [comment]
ok if one uses the code I implemented above, it seems at least in 1 experiment that pwcca passes the sanity check I was worried (although as in the random baseline code above it doesn't always pass it due to numerical differences it seems between pytorch and numpy) but hopefully if one uses the other three metrics one can have confidence in the experiments results + pwcca will only give issues when number are close to zero e.g. `e-12`.

**Comment by brando90** [comment]
Hi @moskomule , are these asserts correct for your code? (note one is square so I assert passes but would like to know if the symbolic letters are correct:
```
    D1 = x.size(1)
    D2 = y.size(1)
    a, b, diag = cca(x, y, backend)
    C = diag.size(0)
    assert a.size() == torch.Size([D1, C])
    assert b.size() == torch.Size([D2, C])
```

in particular the assert for `a`

**Comment by moskomule** [comment]
Yes, check the latest test.

**Comment by brando90** [comment]
> Yes, when I first implemented `cca.pytorch`, the scalability was the problem for a researcher without rich resources.

can't you compute covariance easily as follow:
```
        sigma_xx_approx = L1.T @ L1
        sigma_yy_approx = L2.T @ L2
```
?

**Comment by brando90** [comment]
I think inverting them is the main issues...
